/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import data.*;
import entidades.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Veronica
 */
public class JPAltasYBajas extends javax.swing.JPanel {

    Cliente cliente = new Cliente();
    ClienteData cd = new ClienteData();
    Mascota mascota = new Mascota();
    MascotaData md = new MascotaData();

    /**
     * Creates new form AltasYBajas
     */
    public JPAltasYBajas() {
        initComponents();
        controlBotonesCliente(true, false, false);
        controlBotonesMascota(true, false, false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jtfDNI = new javax.swing.JTextField();
        jbActivarCliente = new javax.swing.JButton();
        jbDesactivarCliente = new javax.swing.JButton();
        jlNombreCliente = new javax.swing.JLabel();
        jbBuscarDNI = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jtfCodigoMascota = new javax.swing.JTextField();
        jbBuscarMascota = new javax.swing.JButton();
        jbActivarMascota = new javax.swing.JButton();
        jbDesactivarMascota = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jlDatosMascota = new javax.swing.JLabel();
        jbLimpiarGral = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(700, 450));
        setMinimumSize(new java.awt.Dimension(700, 450));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(700, 70));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel1.setText("Altas y Bajas");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 210, 49));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/down.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, 40, 60));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/up.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 30, 60));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 60));

        jPanel2.setBackground(new java.awt.Color(245, 245, 245));
        jPanel2.setPreferredSize(new java.awt.Dimension(700, 350));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 700, 10));

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel4.setText("DNI del cliente");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 100, 30));

        jtfDNI.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jPanel2.add(jtfDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 160, 50));

        jbActivarCliente.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jbActivarCliente.setText("Activar");
        jbActivarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbActivarClienteActionPerformed(evt);
            }
        });
        jPanel2.add(jbActivarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 40, 100, 50));

        jbDesactivarCliente.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jbDesactivarCliente.setText("Desactivar");
        jbDesactivarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDesactivarClienteActionPerformed(evt);
            }
        });
        jPanel2.add(jbDesactivarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 40, -1, 50));

        jlNombreCliente.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jPanel2.add(jlNombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 510, 40));

        jbBuscarDNI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/outline_search_black_24dp.png"))); // NOI18N
        jbBuscarDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarDNIActionPerformed(evt);
            }
        });
        jPanel2.add(jbBuscarDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 60, 50));

        jLabel5.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel5.setText("Codigo Mascota");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 120, 30));

        jtfCodigoMascota.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jPanel2.add(jtfCodigoMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 160, 50));

        jbBuscarMascota.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/outline_search_black_24dp.png"))); // NOI18N
        jbBuscarMascota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarMascotaActionPerformed(evt);
            }
        });
        jPanel2.add(jbBuscarMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 60, 50));

        jbActivarMascota.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jbActivarMascota.setText("Activar");
        jbActivarMascota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbActivarMascotaActionPerformed(evt);
            }
        });
        jPanel2.add(jbActivarMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 160, 100, 50));

        jbDesactivarMascota.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jbDesactivarMascota.setText("Desactivar");
        jbDesactivarMascota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDesactivarMascotaActionPerformed(evt);
            }
        });
        jPanel2.add(jbDesactivarMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 160, -1, 50));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 218, 700, 10));

        jlDatosMascota.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jPanel2.add(jlDatosMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 104, 540, 50));

        jbLimpiarGral.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jbLimpiarGral.setText("Limpiar");
        jbLimpiarGral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimpiarGralActionPerformed(evt);
            }
        });
        jPanel2.add(jbLimpiarGral, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 320, -1, 50));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 700, 390));
    }// </editor-fold>//GEN-END:initComponents

    private void jbBuscarDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarDNIActionPerformed
        try {
            int dni = Integer.parseInt(jtfDNI.getText());
            cliente = cd.buscarTodoClientePorDni(dni);
            jlNombreCliente.setText(cliente.getNombre() + "  " + cliente.getApellido() + " ");
            if (cliente.isActivo()) {
                jbActivarCliente.setEnabled(false);
                jbDesactivarCliente.setEnabled(true);
            } else {
                jbActivarCliente.setEnabled(true);
                jbDesactivarCliente.setEnabled(false);
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Solo debe ingresar números. " + ex);
            jtfDNI.setText("");
        } catch (NullPointerException ex) {
            JOptionPane.showMessageDialog(this, "Complete el campo requerido. " + ex);
            jtfDNI.setText("");
        }
    }//GEN-LAST:event_jbBuscarDNIActionPerformed

    private void jbDesactivarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDesactivarClienteActionPerformed
        int dni = Integer.parseInt(jtfDNI.getText());
        cliente = cd.buscarTodoClientePorDni(dni);
        cd.eliminarCliente(cliente.getIdCliente());
        jtfDNI.setText("");
        jlNombreCliente.setText("");
        controlBotonesCliente(true, false, false);
    }//GEN-LAST:event_jbDesactivarClienteActionPerformed

    private void jbActivarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbActivarClienteActionPerformed
        int dni = Integer.parseInt(jtfDNI.getText());
        cd.activarCliente(dni);
        jtfDNI.setText("");
        jlNombreCliente.setText("");
        controlBotonesCliente(true, false, false);
    }//GEN-LAST:event_jbActivarClienteActionPerformed

    private void jbBuscarMascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarMascotaActionPerformed

        try {
            int idMascota = Integer.parseInt(jtfCodigoMascota.getText());
            mascota = md.buscarMascota(idMascota);
            jlDatosMascota.setText(mascota.getAlias() + ", " + mascota.getEspecie() + ",  (" + mascota.getColores() + "),  " + mascota.getRaza());
            if (mascota.isActivo()) {
                controlBotonesMascota(false, false, true);
            } else {
                controlBotonesMascota(false, true, false);
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Solo debe ingresar números. " + ex);
            jtfDNI.setText("");
        } catch (NullPointerException ex) {
            JOptionPane.showMessageDialog(this, "Complete el campo requerido. " + ex);
            jtfDNI.setText("");
        }
    }//GEN-LAST:event_jbBuscarMascotaActionPerformed

    private void jbActivarMascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbActivarMascotaActionPerformed
        int idMascota = Integer.parseInt(jtfCodigoMascota.getText());
        md.reactivarMascota(idMascota);
        jtfCodigoMascota.setText("");
        jlDatosMascota.setText("");
        controlBotonesMascota(true, false, false);
    }//GEN-LAST:event_jbActivarMascotaActionPerformed

    private void jbDesactivarMascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDesactivarMascotaActionPerformed
        int idMascota = Integer.parseInt(jtfCodigoMascota.getText());
        md.bajaMascota(idMascota);
        jtfCodigoMascota.setText("");
        jlDatosMascota.setText("");
        controlBotonesMascota(true, false, false);
    }//GEN-LAST:event_jbDesactivarMascotaActionPerformed

    private void jbLimpiarGralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimpiarGralActionPerformed
        controlBotonesCliente(true, false, false);
        controlBotonesMascota(true, false, false);
        jtfDNI.setText("");
        jtfCodigoMascota.setText("");
        jlNombreCliente.setText("");
        jlDatosMascota.setText("");
    }//GEN-LAST:event_jbLimpiarGralActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton jbActivarCliente;
    private javax.swing.JButton jbActivarMascota;
    private javax.swing.JButton jbBuscarDNI;
    private javax.swing.JButton jbBuscarMascota;
    private javax.swing.JButton jbDesactivarCliente;
    private javax.swing.JButton jbDesactivarMascota;
    private javax.swing.JButton jbLimpiarGral;
    private javax.swing.JLabel jlDatosMascota;
    private javax.swing.JLabel jlNombreCliente;
    private javax.swing.JTextField jtfCodigoMascota;
    private javax.swing.JTextField jtfDNI;
    // End of variables declaration//GEN-END:variables

    public void controlBotonesCliente(boolean buscar, boolean activar, boolean desactivar) {
        jbBuscarDNI.setEnabled(buscar);
        jbActivarCliente.setEnabled(activar);
        jbDesactivarCliente.setEnabled(desactivar);
    }

    public void controlBotonesMascota(boolean buscar, boolean activar, boolean desactivar) {
        jbBuscarMascota.setEnabled(buscar);
        jbActivarMascota.setEnabled(activar);
        jbDesactivarMascota.setEnabled(desactivar);
    }

}
